### ISSUE TITLE
Coap gateway replicas parameter is being ignored with helm charts

### ISSUE THREAD

**Issue by itestoss** [plgd-dev/hub#629]
### Description
When deploying plgd via helm chart and a file to override some parameters the replicas value for COAP gateway is being ignored.
(PS: looks like it is being read from resource directory instead, because if one increases it's replicas value, them the COAP gateway also increases the number of replicas by the same amount)

### How can it be reproduced?
1. deploy using command:
microk8s.helm3 install am-1 -f withMock.yaml plgd/plgd-hub --create-namespace --namespace=am-1 --version 2.2.2

withMock.yaml content:

```
global:
  domain: "host.domain.com"
  hubId: "d03a1bb4-0a77-428c-b78c-1c46efe6a38e"
mockoauthserver:
  enabled: true
coapgateway:
  replicas: 3
  port: 5683
  service:
    type: NodePort
    nodePort: 5683
  apis:
    coap:
      tls:
        enabled: false
```

2. Check deployed pods:
  microk8s.kubectl get pods -A

### Logs, error output, etc.
Only one plgd-hub-coap-gateway pod is running after deploy of the helm chart with replicas: 3 overridden.

### Environment
- microk8s v1.22.4 (snap) running on CentOS Linux release 8.5.2111
- microk8s helm3 v3.5.0
- plgd hub tag: 2.2.2
